#!/bin/bash
# ================================================================
# 02-install-gitlab.sh — Install GitLab CE via Omnibus
# ================================================================
# Installs GitLab CE Omnibus package on the VM, writes gitlab.rb,
# and runs gitlab-ctl reconfigure.
#
# Prerequisites:
#   - VM provisioned (01-provision-vm.sh) with SSH access
#   - Internet access on VM for apt repo
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

VM_SSH="ssh ${SSH_OPTS} root@${VM_IP%/*}"

echo "=== Installing GitLab CE Omnibus on ${VM_NAME} (${VM_IP%/*}) ==="
echo ""

# ---------------------------------------------------------------
# Step 0: Check Internet connectivity on VM
# ---------------------------------------------------------------
echo "[0/6] Verificando conectividad a Internet desde la VM..."

VM_CONNECTED=$(${VM_SSH} "curl -sf --connect-timeout 10 -o /dev/null -w '%{http_code}' https://packages.gitlab.com 2>/dev/null || echo 'FAIL'")
VM_APT_REACHABLE=$(${VM_SSH} "curl -sf --connect-timeout 10 -o /dev/null -w '%{http_code}' https://archive.ubuntu.com 2>/dev/null || echo 'FAIL'")
VM_DNS_OK=$(${VM_SSH} "nslookup google.com 2>/dev/null | grep -q 'Address' && echo 'OK' || echo 'FAIL'")

CONNECT_ERRORS=""
[ "${VM_DNS_OK}" = "FAIL" ] && CONNECT_ERRORS="${CONNECT_ERRORS} DNS_FAIL"
[ "${VM_APT_REACHABLE}" = "FAIL" ] && CONNECT_ERRORS="${CONNECT_ERRORS} APT_REPO_UNREACHABLE"
[ "${VM_CONNECTED}" = "FAIL" ] && CONNECT_ERRORS="${CONNECT_ERRORS} GITLAB_REPO_UNREACHABLE"

if [ -n "${CONNECT_ERRORS}" ]; then
    echo "❌ La VM no tiene conectividad a Internet:"
    echo "${VM_DNS_OK}" | grep -q "FAIL" && echo "   - DNS: no resuelve google.com" || echo "   - DNS: OK"
    echo "${VM_APT_REACHABLE}" | grep -q "FAIL" && echo "   - APT repo: archive.ubuntu.com inalcanzable" || echo "   - APT repo: OK"
    echo "${VM_CONNECTED}" | grep -q "FAIL" && echo "   - GitLab repo: packages.gitlab.com inalcanzable" || echo "   - GitLab repo: OK"

    echo ""
    echo "  Posibles causas:"
    echo "  - La VM no tiene gateway configurado (verificar VM_GATEWAY en 00-env.sh)"
    echo "  - El bridge vmbr0 no tiene salida a Internet"
    echo "  - Firewall de red bloquea tráfico saliente"
    echo "  - El cloud-init no configuró correctamente la red"
    echo ""
    echo "  Para diagnosticar:"
    echo "    ssh root@${VM_IP%/*} 'ip route show default && ping -c 2 8.8.8.8'"
    echo ""
    echo "Abortando. Corrija la conectividad de red y vuelva a ejecutar."
    exit 1
fi

echo "[0/6] ✅ VM con conectividad a Internet (DNS: OK, APT: OK, GitLab repo: OK)"
echo ""

# ---------------------------------------------------------------
# Step 1: Install dependencies and Omnibus repo
# ---------------------------------------------------------------
echo "[1/6] Instalando dependencias y repo Omnibus..."

${VM_SSH} bash -s << 'REMOTE'
    set -euo pipefail
    apt-get update -qq
    apt-get install -y -qq curl openssh-server ca-certificates tzdata perl

    # Add GitLab Omnibus repository
    curl -fsSL https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
    echo "✅ Repo Omnibus agregado"
REMOTE

# ---------------------------------------------------------------
# Step 2: Install GitLab CE package
# ---------------------------------------------------------------
echo ""
echo "[2/6] Instalando GitLab CE..."

${VM_SSH} bash -s << 'REMOTE'
    set -euo pipefail
    apt-get install -y gitlab-ce
    echo "✅ GitLab CE instalado"
REMOTE

# ---------------------------------------------------------------
# Step 3: Write gitlab.rb configuration
# ---------------------------------------------------------------
echo ""
echo "[3/6] Escribiendo /etc/gitlab/gitlab.rb..."

# We write the config file via SSH heredoc
${VM_SSH} bash -s -- \
    "${GITLAB_DOMAIN}" "${GITLAB_SSH_PORT}" "${GITLAB_LETSENCRYPT_EMAIL}" << 'REMOTE'
    set -euo pipefail
    DOMAIN="$1"; SSH_PORT="$2"; LE_EMAIL="$3"

    cat > /etc/gitlab/gitlab.rb << 'GITLAB_RB'
# ================================================================
# gitlab.rb — GitLab Omnibus Configuration
# Generated by 02-install-gitlab.sh — DO NOT EDIT MANUALLY
# Use /etc/gitlab/gitlab.rb.d/ or gitlab-ctl reconfigure
# ================================================================

# --- External URL ---
external_url 'https://__GITLAB_DOMAIN__'

# --- Let's Encrypt ---
letsencrypt['enable'] = true
letsencrypt['contact_emails'] = ['__LE_EMAIL__']
letsencrypt['auto_renew'] = true
letsencrypt['auto_renew_hour'] = 3
letsencrypt['auto_renew_minute'] = 30

# --- NGINX ---
nginx['listen_port'] = 80
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {
  'X-Forwarded-Proto' => 'https',
  'X-Forwarded-Ssl' => 'on'
}

# Trusted proxies (add reverse proxy IPs if behind one)
# gitlab_rails['trusted_proxies'] = ['192.168.1.0/24']

# --- SSH Git ---
gitlab_rails['gitlab_shell_ssh_port'] = __SSH_PORT__
gitlab_sshd['enable'] = true

# --- PostgreSQL (bundled) ---
postgresql['enable'] = true
postgresql['shared_buffers'] = "256MB"

# --- Redis (bundled) ---
redis['enable'] = true

# --- Puma ---
puma['worker_processes'] = 2
puma['min_threads'] = 4
puma['max_threads'] = 8

# --- Sidekiq ---
sidekiq['max_concurrency'] = 10

# --- Backups ---
gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
gitlab_rails['backup_archive_permissions'] = 0644
gitlab_rails['backup_keep_time'] = 604800  # 7 days

# --- LDAP (disabled — activate when SSO is ready) ---
# gitlab_rails['ldap_enabled'] = true
# gitlab_rails['ldap_servers'] = {
#   'main' => {
#     'label' => 'LDAP',
#     'host' => 'ldap.gidas.local',
#     'port' => 389,
#     'uid' => 'cn',
#     'encryption' => 'start_tls',
#     'base' => 'dc=gidas,dc=local',
#     'active_directory' => true,
#     'allow_username_or_email_login' => false,
#     'block_auto_created_users' => false
#   }
# }

# --- Monitoring ---
# Prometheus exporter (bundled)
prometheus['enable'] = true
GITLAB_RB

    # Replace placeholders
    sed -i "s/__GITLAB_DOMAIN__/${DOMAIN}/g" /etc/gitlab/gitlab.rb
    sed -i "s/__LE_EMAIL__/${LE_EMAIL}/g" /etc/gitlab/gitlab.rb
    sed -i "s/__SSH_PORT__/${SSH_PORT}/g" /etc/gitlab/gitlab.rb

    echo "✅ /etc/gitlab/gitlab.rb escrito"
REMOTE

# ---------------------------------------------------------------
# Step 4: Reconfigure GitLab
# ---------------------------------------------------------------
echo ""
echo "[4/6] Ejecutando gitlab-ctl reconfigure..."

${VM_SSH} "gitlab-ctl reconfigure" || {
    echo "❌ gitlab-ctl reconfigure falló — verificar logs en /var/log/gitlab"
    echo "  Comando: ssh root@${VM_IP%/*} tail -50 /var/log/gitlab/reconfigure"
    exit 1
}
echo "[4/6] ✅ gitlab-ctl reconfigure completado"

# ---------------------------------------------------------------
# Step 5: Verify services
# ---------------------------------------------------------------
echo ""
echo "[5/6] Verificando servicios GitLab..."

${VM_SSH} "gitlab-ctl status" && {
    echo "[5/6] ✅ Todos los servicios GitLab activos"
}

echo ""
echo "=== GitLab CE installation complete ==="
echo "  URL: https://${GITLAB_DOMAIN}"
echo "  SSH port: ${GITLAB_SSH_PORT}"
echo ""
echo "Next: run 03-configure-https.sh"
