#!/bin/bash
# ================================================================
# 03-deploy-stack.sh — Phase 3: Deploy Docker Compose Stack
# ================================================================
# SCP docker-compose.yml + .env a la VM, ejecuta compose up -d
# y valida estado de los servicios.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=00-env.sh
. "${SCRIPT_DIR}/00-env.sh"

echo "=== Phase 3: Deploy Redmine Stack on ${VM_FQDN} ==="

# --- Step 1: Ensure remote directories exist ---
echo "[Step 1] Creating remote directories..."
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "mkdir -p ~/redmine/nginx/ssl"

# --- Step 2: Generate .env from current session vars ---
echo "[Step 2] Generating .env with secrets..."
cat > /tmp/redmine-env-$$ <<EOF
# Redmine Stack — Auto-generated by 03-deploy-stack.sh
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDMINE_SECRET_KEY=${REDMINE_SECRET_KEY}
REDMINE_VERSION=${REDMINE_VERSION}
POSTGRES_VERSION=${POSTGRES_VERSION}
NGINX_VERSION=${NGINX_VERSION}
EOF

# --- Step 3: SCP files to VM ---
echo "[Step 3] Copying docker-compose.yml and .env to ${VM_FQDN}..."
scp ${SSH_OPTS} "${SCRIPT_DIR}/docker-compose.yml" "${VM_USER}@${VM_IP}:~/redmine/docker-compose.yml"
scp ${SSH_OPTS} /tmp/redmine-env-$$ "${VM_USER}@${VM_IP}:~/redmine/.env"
rm -f /tmp/redmine-env-$$

# --- Step 4: Deploy stack ---
echo "[Step 4] Running docker compose up -d..."
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "cd ~/redmine && docker compose pull && docker compose up -d"

# --- Step 5: Wait for services to be healthy ---
echo "[Step 5] Waiting for stack readiness (up to 90s)..."
for i in $(seq 1 18); do
    sleep 5
    STATUS=$(ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
        "cd ~/redmine && docker compose ps --format '{{.Name}} {{.Status}}' 2>/dev/null || true")
    # Check if all services are running (Up)
    ALL_UP=$(echo "${STATUS}" | grep -v "Up" | wc -l)
    if [ "${ALL_UP}" -eq 0 ]; then
        echo "[Step 5] All services are running ✓"
        echo "${STATUS}"
        break
    fi
    echo "[Step 5] Waiting... ($((i * 5))s)"
    if [ "$i" -eq 18 ]; then
        echo "WARNING: Not all services show 'Up' after 90s. Status:"
        echo "${STATUS}"
    fi
done

# --- Step 6: Validate Redmine HTTP response ---
echo "[Step 6] Validating Redmine HTTP on localhost:3000..."
HTTP_CODE=$(ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "curl -s -o /dev/null -w '%{http_code}' http://localhost:3000/login 2>/dev/null || echo '000'")
if [ "${HTTP_CODE}" = "200" ]; then
    echo "[Step 6] Redmine responds with HTTP ${HTTP_CODE} ✓"
elif [ "${HTTP_CODE}" = "302" ]; then
    echo "[Step 6] Redmine responds with HTTP ${HTTP_CODE} (redirect — acceptable) ✓"
else
    echo "WARNING: Redmine HTTP status: ${HTTP_CODE}. Check with: docker compose logs redmine"
fi

echo ""
echo "=== Phase 3 complete: Redmine stack deployed ==="
echo "    Internal: http://localhost:3000 (within VM)"
echo "    Next: ./04-configure-ssl.sh"
