#!/bin/bash
# ================================================================
# 05-backup.sh — Phase 5: Backups + Cron
# ================================================================
# pg_dump via docker exec + tarball de volúmenes files/plugins/themes.
# Cada volumen se guarda como archivo individual (no combinado).
# Opcional: --install-cron para desplegar script standalone en la VM
# y configurar cron diario a las 02:00.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=00-env.sh
. "${SCRIPT_DIR}/00-env.sh"

DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR_REMOTE="${BACKUP_DIR}"
DB_BACKUP="${BACKUP_DIR_REMOTE}/db/redmine_${DATE}.sql.gz"
RETENTION_DAYS=14

echo "=== Phase 5: Backup Redmine on ${VM_FQDN} ==="

# --- Step 1: Create backup directories ---
echo "[Step 1] Creating backup directories on remote VM..."
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "sudo mkdir -p ${BACKUP_DIR_REMOTE}/db ${BACKUP_DIR_REMOTE}/files && \
     sudo chown -R ${VM_USER}:${VM_USER} ${BACKUP_DIR_REMOTE}"

# --- Step 2: Database dump via pg_dump ---
echo "[Step 2] Running pg_dump via docker exec..."
PG_CONTAINER=$(ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" "docker ps --format '{{.Names}}' | grep redmine-postgres" 2>/dev/null || echo "")
if [ -z "${PG_CONTAINER}" ]; then
    echo "ERROR: PostgreSQL container not found. Is the stack running?"
    exit 1
fi
echo "[Step 2] Using container: ${PG_CONTAINER}"

ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "docker exec ${PG_CONTAINER} pg_dump -U ${POSTGRES_USER} ${POSTGRES_DB} | gzip > ${DB_BACKUP}"
echo "[Step 2] Database dump created: ${DB_BACKUP}"

# --- Step 3: Validate dump integrity ---
echo "[Step 3] Validating dump integrity with gunzip -t..."
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" "gunzip -t ${DB_BACKUP}"
echo "[Step 3] Dump integrity check passed ✓"

DUMP_SIZE=$(ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" "ls -lh ${DB_BACKUP} 2>/dev/null | awk '{print \$5}'" || echo "?")
echo "[Step 3] Dump size: ${DUMP_SIZE}"

# --- Step 4: Backup files/plugins/themes volumes (individual tarballs) ---
# Each volume gets its own file — no concatenation (fixes multi-member gzip bug).
echo "[Step 4] Creating tarballs of files/plugins/themes volumes..."
for VOLUME in redmine_files redmine_plugins redmine_themes; do
    echo "[Step 4] Backing up volume ${VOLUME}..."
    ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
        "docker run --rm -v ${VOLUME}:/data -v ${BACKUP_DIR_REMOTE}/files:/backup \
            alpine tar czf /backup/${VOLUME}_${DATE}.tar.gz -C /data . 2>/dev/null" || \
        echo "WARNING: Volume ${VOLUME} backup skipped (may not exist yet)."
done

# --- Step 5: Validate volume tarballs ---
echo "[Step 5] Validating volume tarballs..."
for VOLUME in redmine_files redmine_plugins redmine_themes; do
    TAR_FILE="${BACKUP_DIR_REMOTE}/files/${VOLUME}_${DATE}.tar.gz"
    ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
        "tar tzf ${TAR_FILE} 2>/dev/null | head -3" || \
        echo "[Step 5] Note: ${VOLUME} tarball may be empty if volume has no data yet."
done

# --- Step 6: Cleanup old backups ---
echo "[Step 6] Cleaning backups older than ${RETENTION_DAYS} days..."
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "find ${BACKUP_DIR_REMOTE}/db -name 'redmine_*.sql.gz' -mtime +${RETENTION_DAYS} -delete && \
     find ${BACKUP_DIR_REMOTE}/files -name 'redmine_*.tar.gz' -mtime +${RETENTION_DAYS} -delete"
echo "[Step 6] Cleanup complete. Keeping backups from last ${RETENTION_DAYS} days."

# --- Step 7: Summary ---
echo "[Step 7] Backup summary:"
ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
    "echo '  DB:      ' && ls -lh ${DB_BACKUP} 2>/dev/null | awk '{print \$5, \$NF}' && \
     echo '  Files:   ' && ls -lh ${BACKUP_DIR_REMOTE}/files/redmine_files_${DATE}.tar.gz 2>/dev/null | awk '{print \$5, \$NF}' && \
     echo '  Plugins: ' && ls -lh ${BACKUP_DIR_REMOTE}/files/redmine_plugins_${DATE}.tar.gz 2>/dev/null | awk '{print \$5, \$NF}' && \
     echo '  Themes:  ' && ls -lh ${BACKUP_DIR_REMOTE}/files/redmine_themes_${DATE}.tar.gz 2>/dev/null | awk '{print \$5, \$NF}' && \
     echo '  Total:   ' && du -sh ${BACKUP_DIR_REMOTE} 2>/dev/null | awk '{print \$1}'"

echo ""
echo "=== Backup complete ==="

# --- Optional: Install cron ---
# Deploys a standalone backup script to the VM and installs a daily cron entry.
# The standalone script runs directly on the VM (no SSH, no dev machine dependencies).
if [ "${1:-}" = "--install-cron" ]; then
    echo ""
    echo "=== Installing daily cron at 02:00 ==="

    # Generate standalone backup script for the VM
    CRON_SCRIPT="/tmp/redmine-cron-backup-$$"
    cat > "${CRON_SCRIPT}" << 'CRONEOF'
#!/bin/bash
# ================================================================
# 05-backup.sh — VM-local cron backup script
# Auto-generated by --install-cron on the dev machine.
# Runs directly on the VM — no SSH or dev machine needed.
# ================================================================
set -euo pipefail

DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="/var/backups/redmine"
DB_BACKUP="${BACKUP_DIR}/db/redmine_${DATE}.sql.gz"
RETENTION_DAYS=14

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting Redmine backup..."

# Ensure directories exist
sudo mkdir -p "${BACKUP_DIR}/db" "${BACKUP_DIR}/files"
sudo chown -R infra:infra "${BACKUP_DIR}"

# DB dump
PG_CONTAINER=$(docker ps --format '{{.Names}}' | grep redmine-postgres || true)
if [ -z "${PG_CONTAINER}" ]; then
    echo "ERROR: PostgreSQL container not found. Is the stack running?"
    exit 1
fi
echo "[DB] Using container: ${PG_CONTAINER}"
docker exec "${PG_CONTAINER}" pg_dump -U redmine redmine | gzip > "${DB_BACKUP}"
echo "[DB] Dump created: ${DB_BACKUP}"

# Validate dump
gunzip -t "${DB_BACKUP}"
echo "[DB] Integrity check passed ✓"

# Volume backups (individual per-volume files — no concatenation)
for VOLUME in redmine_files redmine_plugins redmine_themes; do
    echo "[VOL] Backing up ${VOLUME}..."
    docker run --rm -v "${VOLUME}:/data" -v "${BACKUP_DIR}/files:/backup" \
        alpine tar czf "/backup/${VOLUME}_${DATE}.tar.gz" -C /data . 2>/dev/null || \
        echo "[VOL] WARNING: ${VOLUME} backup skipped (may not exist yet)."
done

# Cleanup old backups
find "${BACKUP_DIR}/db" -name 'redmine_*.sql.gz' -mtime +${RETENTION_DAYS} -delete 2>/dev/null || true
find "${BACKUP_DIR}/files" -name 'redmine_*.tar.gz' -mtime +${RETENTION_DAYS} -delete 2>/dev/null || true

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Backup complete"
CRONEOF

    # SCP the standalone script to VM
    REMOTE_SCRIPT="~/redmine/05-backup.sh"
    scp ${SSH_OPTS} "${CRON_SCRIPT}" "${VM_USER}@${VM_IP}:${REMOTE_SCRIPT}"
    rm -f "${CRON_SCRIPT}"

    # Make it executable on the VM
    ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" "chmod +x ${REMOTE_SCRIPT}"

    # Install cron entry referencing the VM-local script
    CRON_LINE="0 2 * * * ${VM_USER} ${REMOTE_SCRIPT} >> ${BACKUP_DIR_REMOTE}/backup.log 2>&1"
    ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" \
        "(crontab -l 2>/dev/null | grep -v '05-backup.sh'; echo '${CRON_LINE}') | crontab -"
    echo "[Cron] Daily backup scheduled: 02:00 daily"
    echo "[Cron] Script deployed to VM: ${REMOTE_SCRIPT}"
    ssh ${SSH_OPTS} "${VM_USER}@${VM_IP}" "crontab -l | grep redmine || echo 'No redmine cron found.'"
    echo "=== Cron installed ==="
fi
