#!/bin/bash
# ================================================================
# 02-configure-nfs.sh — Tasks T-05, T-10: Configure NFS exports
# ================================================================
# Configures NFS exports for all datasets, kernel tuning, and
# adds NFS storage in Proxmox via pvesm.
#
# Prerequisites:
#   1. T-04 completed — pool ${SHARED_POOL} exists with datasets
#   2. Run on pve-desa03 as root (for exports + sysctl)
#   3. pvesm add runs from any cluster node (pmxcfs syncs)
#
# IDEMPOTENT: safe to run multiple times.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

echo "=== Tasks T-05, T-10: Configure NFS exports + pvesm ==="
echo ""

# ---------------------------------------------------------------
# Step 1: Verify we're on pve-desa03
# ---------------------------------------------------------------
echo "[1/6] Verifying execution context..."

CURRENT_HOST=$(hostname -s 2>/dev/null || echo "unknown")
if [ "${CURRENT_HOST}" != "${SHARED_NODE_NAME}" ]; then
    echo "❌ NFS exports must be configured on ${SHARED_NODE_NAME} (${SHARED_NODE_IP})."
    echo "   Current host: ${CURRENT_HOST}"
    exit 1
fi
echo "[1/6] ✅ Running on ${CURRENT_HOST}"

# ---------------------------------------------------------------
# Step 2: Verify pool exists
# ---------------------------------------------------------------
echo ""
echo "[2/6] Verifying ${SHARED_POOL} pool and datasets exist..."

if ! zpool list -H -o name 2>/dev/null | grep -q "^${SHARED_POOL}$"; then
    echo "❌ Pool ${SHARED_POOL} not found. Run 01-create-datasets.sh first."
    exit 1
fi

# Verify all NFS datasets exist
MISSING=false
for ds in "${NFS_DATASETS[@]}"; do
    if ! zfs list -H -o name 2>/dev/null | grep -q "^${SHARED_POOL}/${ds}$"; then
        echo "❌ Dataset ${SHARED_POOL}/${ds} not found"
        MISSING=true
    fi
done

# Verify samba dataset exists (for non-NFS export)
if ! zfs list -H -o name 2>/dev/null | grep -q "^${SHARED_POOL}/samba$"; then
    echo "❌ Dataset ${SHARED_POOL}/samba not found"
    MISSING=true
fi

if [ "${MISSING}" = true ]; then
    echo "Run 01-create-datasets.sh first to create all datasets."
    exit 1
fi
echo "[2/6] ✅ All datasets verified"

# ---------------------------------------------------------------
# Step 3: Write /etc/exports (T-05)
# ---------------------------------------------------------------
echo ""
echo "[3/6] Writing /etc/exports..."

# Backup existing exports
if [ -f /etc/exports ] && ! grep -q "^/${SHARED_POOL}" /etc/exports 2>/dev/null; then
    cp /etc/exports "/etc/exports.bak.$(date +%Y%m%d)"
    echo "[3/6] Existing exports backed up"
fi

# Build exports file
FSID_BASE=100
{
    echo "# /etc/exports — Shared ZFS datasets (generated by F3)"
    echo "# Generated: $(date)"
    echo "# Changes require: exportfs -ra"
    echo ""

    for ds in "${NFS_DATASETS[@]}"; do
        FSID=$((FSID_BASE))
        EXPORT_PATH="/${SHARED_POOL}/${ds}"
        echo "${EXPORT_PATH} ${NFS_SUBNET}(${NFS_OPTIONS},fsid=${FSID})"
        FSID_BASE=$((FSID_BASE + 1))
    done

    echo ""
    echo "# samba dataset — NFS to localhost only (for Samba access)"
    echo "/${SHARED_POOL}/samba 127.0.0.1(rw,async,no_subtree_check)"
} > /etc/exports

echo "[3/6] ✅ /etc/exports written:"
cat /etc/exports

# Apply exports
echo ""
echo "[3/6] Applying exports (exportfs -ra)..."
exportfs -ra

# Verify exports
echo "[3/6] Current exports:"
showmount -e localhost 2>/dev/null || exportfs -v

# ---------------------------------------------------------------
# Step 4: NFS kernel tuning (sysctl)
# ---------------------------------------------------------------
echo ""
echo "[4/6] Configuring NFS kernel tuning..."

if [ ! -f "${NFS_SYSCTL_CONF}" ] || ! grep -q "tcp_slot_table_entries" "${NFS_SYSCTL_CONF}" 2>/dev/null; then
    cat >> "${NFS_SYSCTL_CONF}" << 'EOF'

# NFS tuning for async exports over 1 GbE
sunrpc.tcp_slot_table_entries=128
sunrpc.tcp_max_slot_table_entries=128
EOF
    echo "[4/6] ✅ ${NFS_SYSCTL_CONF} written"
else
    echo "[4/6] ⏭️  ${NFS_SYSCTL_CONF} already configured"
fi

sysctl -p "${NFS_SYSCTL_CONF}" 2>/dev/null || {
    echo "[4/6] ⚠️  sysctl -p failed. Check kernel module: sunrpc loaded?"
    echo "   (Will apply on next reboot if module loads after)"
}

# Ensure NFS server is running
echo ""
echo "[4/6] Ensuring NFS server is enabled and running..."
systemctl enable nfs-server nfs-kernel-server 2>/dev/null || true
systemctl start nfs-server nfs-kernel-server 2>/dev/null || true

NFS_ACTIVE=$(systemctl is-active nfs-server 2>/dev/null || echo "unknown")
if [ "${NFS_ACTIVE}" = "active" ] || systemctl is-active nfs-kernel-server &>/dev/null; then
    echo "[4/6] ✅ NFS server is active"
else
    echo "❌ NFS server failed to start. Check: journalctl -u nfs-server"
    exit 1
fi

# ---------------------------------------------------------------
# Step 5: Add NFS storage in Proxmox (T-10, T-11)
# ---------------------------------------------------------------
echo ""
echo "[5/6] Adding NFS storages in Proxmox (pvesm)..."
echo ""

# Check if pvesm is available (should be on any Proxmox node)
if ! command -v pvesm &>/dev/null; then
    echo "⚠️  pvesm not available on this node."
    echo "   Run the pvesm add commands from any cluster node:"
fi

for ds in "${NFS_DATASETS[@]}"; do
    STORAGE_ID="${NFS_STORAGE_IDS[${ds}]}"
    CONTENT="${NFS_CONTENT[${ds}]}"
    EXPORT_PATH="/${SHARED_POOL}/${ds}"
    MOUNT_PATH="/mnt/pve/${STORAGE_ID}"
    
    echo "--- Storage: ${STORAGE_ID} (${EXPORT_PATH}) ---"
    
    # Check if already exists
    if pvesm status 2>/dev/null | grep -q "^${STORAGE_ID}\s"; then
        echo "  ⏭️  Storage ${STORAGE_ID} already exists"
        pvesm status 2>/dev/null | grep "^${STORAGE_ID}\s"
    elif command -v pvesm &>/dev/null; then
        echo "  Adding storage ${STORAGE_ID}..."
        pvesm add nfs "${STORAGE_ID}" \
            --server "${SHARED_NODE_IP}" \
            --export "${EXPORT_PATH}" \
            --path "${MOUNT_PATH}" \
            --content "${CONTENT}" \
            --options "vers=4.2,hard,intr,noatime"
        
        if [ $? -eq 0 ]; then
            echo "  ✅ ${STORAGE_ID} added"
        else
            echo "  ⚠️  Failed to add ${STORAGE_ID}. May need to run from cluster node."
        fi
    else
        echo "  Run manually from any cluster node:"
        echo "    pvesm add nfs ${STORAGE_ID} \\"
        echo "      --server ${SHARED_NODE_IP} \\"
        echo "      --export ${EXPORT_PATH} \\"
        echo "      --path ${MOUNT_PATH} \\"
        echo "      --content ${CONTENT} \\"
        echo "      --options vers=4.2,hard,intr,noatime"
    fi
done

# ---------------------------------------------------------------
# Step 6: Final verification
# ---------------------------------------------------------------
echo ""
echo "[6/6] Verification..."
echo ""

echo "--- NFS exports ---"
exportfs -v
echo ""

echo "--- Proxmox storage ---"
if command -v pvesm &>/dev/null; then
    pvesm status 2>/dev/null | grep -E "^shared-|^Name" || echo "  (no shared storages yet)"
fi
echo ""

echo "=== Tasks T-05, T-10 completed ==="
echo ""
echo "✅ /etc/exports configured with ${#NFS_DATASETS[@]} NFS exports"
echo "✅ sysctl NFS tuning applied"
echo "✅ NFS server active"
echo "✅ Proxmox NFS storages added"
echo ""
echo "Next step: Run 03-configure-samba.sh to configure Samba/CIFS"
echo ""
echo "⚠️  Verify from other nodes:"
echo "   showmount -e ${SHARED_NODE_IP}"
echo "   pvesm status (from any cluster node)"
