#!/bin/bash
# ================================================================
# 03-configure-samba.sh — Task T-06: Configure Samba/CIFS
# ================================================================
# Installs and configures Samba to serve the shared-zfs/samba
# dataset as a CIFS share accessible by authenticated users.
#
# Prerequisites:
#   1. T-04 completed — dataset ${SHARED_POOL}/samba exists
#   2. Run on pve-desa03 as root
#
# IDEMPOTENT: safe to run multiple times.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

echo "=== Task T-06: Configure Samba/CIFS ==="
echo ""

# ---------------------------------------------------------------
# Step 1: Verify execution context
# ---------------------------------------------------------------
echo "[1/7] Verifying execution context..."

CURRENT_HOST=$(hostname -s 2>/dev/null || echo "unknown")
if [ "${CURRENT_HOST}" != "${SHARED_NODE_NAME}" ]; then
    echo "❌ Samba must be configured on ${SHARED_NODE_NAME} (${SHARED_NODE_IP})."
    echo "   Current host: ${CURRENT_HOST}"
    exit 1
fi
echo "[1/7] ✅ Running on ${CURRENT_HOST}"

# ---------------------------------------------------------------
# Step 2: Verify samba dataset exists
# ---------------------------------------------------------------
echo ""
echo "[2/7] Verifying ${SHARED_POOL}/samba dataset..."

if ! zfs list -H -o name 2>/dev/null | grep -q "^${SHARED_POOL}/samba$"; then
    echo "❌ Dataset ${SHARED_POOL}/samba not found."
    echo "   Run 01-create-datasets.sh first."
    exit 1
fi
echo "[2/7] ✅ Dataset ${SHARED_POOL}/samba exists at ${SAMBA_SHARE_PATH}"

# ---------------------------------------------------------------
# Step 3: Install Samba if not present
# ---------------------------------------------------------------
echo ""
echo "[3/7] Installing Samba..."

if command -v smbd &>/dev/null; then
    echo "[3/7] ⏭️  Samba already installed ($(smbd --version 2>/dev/null || echo 'version unknown'))"
else
    echo "[3/7] Installing samba package..."
    apt-get update -qq
    apt-get install -y samba
    echo "[3/7] ✅ Samba installed"
fi

# ---------------------------------------------------------------
# Step 4: Write smb.conf (T-06)
# ---------------------------------------------------------------
echo ""
echo "[4/7] Writing Samba configuration..."

# Backup existing config
if [ -f "${SMB_CONF}" ] && ! grep -q "\[${SAMBA_SHARE_NAME}\]" "${SMB_CONF}" 2>/dev/null; then
    cp "${SMB_CONF}" "${SMB_CONF}.bak.$(date +%Y%m%d)"
    echo "[4/7] Existing smb.conf backed up"
fi

cat > "${SMB_CONF}" << EOF
# /etc/samba/smb.conf — Generated by F3 shared storage
# Generated: $(date)
# Changes require: systemctl restart smbd

[global]
   workgroup = ${SAMBA_WORKGROUP}
   server string = ${SAMBA_SERVER_STRING}
   server role = standalone server
   security = user
   map to guest = bad user
   min protocol = SMB3
   max protocol = SMB3
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[${SAMBA_SHARE_NAME}]
   path = ${SAMBA_SHARE_PATH}
   browseable = yes
   read only = no
   guest ok = no
   valid users = @${SAMBA_GROUP}
   create mask = 0755
   directory mask = 0755
   force user = root
   force group = ${SAMBA_GROUP}
EOF

echo "[4/7] ✅ ${SMB_CONF} written"
echo "--- smb.conf snippet ---"
grep -A 10 "\[${SAMBA_SHARE_NAME}\]" "${SMB_CONF}"

# ---------------------------------------------------------------
# Step 5: Create group and user (T-06)
# ---------------------------------------------------------------
echo ""
echo "[5/7] Creating group and user..."

# Create group
if getent group "${SAMBA_GROUP}" &>/dev/null; then
    echo "[5/7] ⏭️  Group ${SAMBA_GROUP} already exists"
else
    groupadd --force "${SAMBA_GROUP}"
    echo "[5/7] ✅ Group ${SAMBA_GROUP} created"
fi

# Create system user
if id "${SAMBA_USER}" &>/dev/null; then
    echo "[5/7] ⏭️  User ${SAMBA_USER} already exists"
else
    useradd -M -s /usr/sbin/nologin -g "${SAMBA_GROUP}" "${SAMBA_USER}"
    echo "[5/7] ✅ User ${SAMBA_USER} created"
fi

# Set SMB password (interactive)
echo ""
echo "[5/7] Setting Samba password for ${SAMBA_USER}..."
if smbpasswd -a "${SAMBA_USER}" 2>/dev/null; then
    echo "[5/7] ✅ Samba password set"
else
    echo "⚠️  smbpasswd failed — you may need to set password manually:"
    echo "    smbpasswd -a ${SAMBA_USER}"
fi

# ---------------------------------------------------------------
# Step 6: Set dataset permissions + restart Samba
# ---------------------------------------------------------------
echo ""
echo "[6/7] Setting permissions and restarting Samba..."

# Ensure share directory exists and has correct ownership
mkdir -p "${SAMBA_SHARE_PATH}"
chown "root:${SAMBA_GROUP}" "${SAMBA_SHARE_PATH}"
chmod 0775 "${SAMBA_SHARE_PATH}"
echo "[6/7] ✅ ${SAMBA_SHARE_PATH}: owner=root:${SAMBA_GROUP}, mode=0775"

# Restart Samba
systemctl enable smbd 2>/dev/null || true
systemctl restart smbd

SMB_STATUS=$(systemctl is-active smbd 2>/dev/null || echo "unknown")
if [ "${SMB_STATUS}" = "active" ]; then
    echo "[6/7] ✅ smbd is active"
else
    echo "❌ smbd failed to start. Check: journalctl -u smbd -n 50"
    exit 1
fi

# ---------------------------------------------------------------
# Step 7: Verification
# ---------------------------------------------------------------
echo ""
echo "[7/7] Verification..."
echo ""

echo "--- Samba status ---"
smbstatus 2>/dev/null | head -15 || echo "  (no active connections)"
echo ""

echo "--- Samba share listing ---"
if command -v smbclient &>/dev/null; then
    smbclient -L "//localhost" -N 2>/dev/null | grep -A 10 "Sharename" || \
        echo "  (smbclient -L failed — may need auth)"
fi
echo ""

echo "--- Dataset permissions ---"
ls -la "${SAMBA_SHARE_PATH}" 2>/dev/null | head -5
echo ""

echo "=== Task T-06 completed ==="
echo ""
echo "✅ Samba installed and configured"
echo "✅ Share: //${SHARED_NODE_IP}/${SAMBA_SHARE_NAME}"
echo "✅ Group: ${SAMBA_GROUP}"
echo "✅ User: ${SAMBA_USER}"
echo ""
echo "⚠️  IMPORTANT: The Samba password was set above."
echo "   If you skipped it, run:  smbpasswd -a ${SAMBA_USER}"
echo ""
echo "Verification from client:"
echo "  smbclient -L //${SHARED_NODE_IP} -U ${SAMBA_USER}"
echo ""
echo "Mount example (Linux client):"
echo "  mount -t cifs //${SHARED_NODE_IP}/${SAMBA_SHARE_NAME} /mnt/shared \\"
echo "    -o vers=3.0,credentials=/etc/samba/credentials,uid=1000,gid=1000"
