#!/bin/bash
# ================================================================
# failover-to-desa02.sh — T-17: DR failover (pve-desa03 → pve-desa02)
# ================================================================
# MANUAL FAILOVER PROCEDURE — NOT AUTOMATED.
# Run on pve-desa02 when pve-desa03 is DOWN or UNREACHABLE.
#
# What this does:
#   1. Verifies pve-desa03 is unreachable
#   2. Promotes DR datasets (local-zfs/backup-dr/*) to read-write
#   3. Installs/starts NFS server and exports them
#   4. Prints instructions for updating Proxmox storage.cfg
#
# PREREQUISITES:
#   - T-16 completed (DR replication has been running)
#   - pve-desa03 is confirmed DOWN
#   - Run on pve-desa02 as root
#
# ⚠️  WARNING: This is a MANUAL procedure. Do NOT automate.
#     Split-brain risk if pve-desa03 comes back during failover.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

echo "========================================================"
echo "  DR Failover: Promote ${DR_NODE_NAME} to NFS server"
echo "========================================================"
echo ""
echo "⚠️  WARNING: Only run this if ${SHARED_NODE_NAME} (${SHARED_NODE_IP})"
echo "   is confirmed DOWN. Running this while both nodes are"
echo "   active will cause SPLIT-BRAIN."
echo ""
echo "   Press Ctrl+C now to abort, or Enter to continue..."
read -r

# ---------------------------------------------------------------
# Step 1: Verify pve-desa03 is unreachable
# ---------------------------------------------------------------
echo ""
echo "[1/5] Verifying ${SHARED_NODE_NAME} is unreachable..."

if ssh -o ConnectTimeout=5 -o BatchMode=yes root@${SHARED_NODE_IP} "hostname" 2>/dev/null; then
    echo ""
    echo "❌ ${SHARED_NODE_NAME} IS REACHABLE. Aborting failover."
    echo "   If ${SHARED_NODE_NAME} is partially up but NFS is broken,"
    echo "   stop nfs-server on ${SHARED_NODE_NAME} first, then re-run."
    exit 1
fi
echo "[1/5] ✅ ${SHARED_NODE_NAME} is unreachable — continuing"

# Also verify we're running on pve-desa02
echo ""
echo "[1/5] Verifying execution context..."
CURRENT_HOST=$(hostname -s 2>/dev/null || echo "unknown")
if [ "${CURRENT_HOST}" != "${DR_NODE_NAME}" ]; then
    echo "❌ This script must run on ${DR_NODE_NAME} (${DR_NODE_IP})."
    echo "   Current host: ${CURRENT_HOST}"
    echo ""
    echo "   Run: ssh root@${DR_NODE_IP} \"bash -s\" < ${SCRIPT_DIR}/failover-to-desa02.sh"
    exit 1
fi
echo "[1/5] ✅ Running on ${CURRENT_HOST}"

# ---------------------------------------------------------------
# Step 2: Verify DR datasets exist
# ---------------------------------------------------------------
echo ""
echo "[2/5] Verifying DR datasets..."

DR_DATASETS="vms kubernetes gitlab registry backups"
MISSING=false
for ds in ${DR_DATASETS}; do
    DS_PATH="${DR_PREFIX}/${ds}"
    if zfs list -H -o name 2>/dev/null | grep -q "^${DS_PATH}$"; then
        echo "[2/5] ✅ ${DS_PATH} exists"
    else
        echo "[2/5] ❌ ${DS_PATH} NOT FOUND"
        MISSING=true
    fi
done

if [ "${MISSING}" = true ]; then
    echo "❌ Some DR datasets are missing. Ensure DR replication"
    echo "   (T-16) has run at least once before failover."
    echo "   Aborting."
    exit 1
fi

# ---------------------------------------------------------------
# Step 3: Promote DR datasets (make them writable)
# ---------------------------------------------------------------
echo ""
echo "[3/5] Promoting DR datasets to read-write..."

for ds in ${DR_DATASETS}; do
    DS_PATH="${DR_PREFIX}/${ds}"
    echo "  Setting readonly=off on ${DS_PATH}..."
    zfs set readonly=off "${DS_PATH}"
    
    # Verify
    CURRENT_RO=$(zfs get readonly -H -o value "${DS_PATH}" 2>/dev/null || echo "unknown")
    if [ "${CURRENT_RO}" = "off" ]; then
        echo "  ✅ ${DS_PATH}: readonly=off"
    else
        echo "  ❌ Failed to set readonly=off on ${DS_PATH}"
        exit 1
    fi
done

echo "[3/5] ✅ All DR datasets promoted to read-write"

# ---------------------------------------------------------------
# Step 4: Export NFS from pve-desa02
# ---------------------------------------------------------------
echo ""
echo "[4/5] Configuring NFS exports on ${DR_NODE_NAME}..."

# Install NFS server if not present
if ! command -v exportfs &>/dev/null; then
    echo "[4/5] Installing nfs-kernel-server..."
    apt-get update -qq
    apt-get install -y nfs-kernel-server
fi

# Write exports file
FSID_BASE=200  # Different fsid range from primary to avoid conflicts
{
    echo "# /etc/exports — DR failover exports (generated by failover-to-desa02.sh)"
    echo "# Generated: $(date)"
    echo "# Active while ${SHARED_NODE_NAME} is down"
    echo ""
    
    for ds in ${DR_DATASETS}; do
        FSID=$((FSID_BASE))
        EXPORT_PATH="/${DR_PREFIX}/${ds}"
        echo "${EXPORT_PATH} ${NFS_SUBNET}(${NFS_OPTIONS},fsid=${FSID})"
        FSID_BASE=$((FSID_BASE + 1))
    done
} > "${EXPORTS_FILE}"

echo "[4/5] ✅ /etc/exports written"
cat "${EXPORTS_FILE}"

# Apply exports
echo ""
echo "[4/5] Applying exports..."
exportfs -ra

# Start NFS server
systemctl enable nfs-server nfs-kernel-server 2>/dev/null || true
systemctl start nfs-server nfs-kernel-server 2>/dev/null || {
    echo "❌ Failed to start NFS server"
    systemctl status nfs-server --no-pager 2>/dev/null | tail -10
    exit 1
}

NFS_ACTIVE=$(systemctl is-active nfs-server 2>/dev/null || echo "unknown")
if [ "${NFS_ACTIVE}" = "active" ]; then
    echo "[4/5] ✅ NFS server active on ${DR_NODE_NAME}"
else
    echo "❌ NFS server not active. Check: journalctl -u nfs-server"
    exit 1
fi

echo ""
echo "[4/5] Current NFS exports:"
showmount -e localhost 2>/dev/null || exportfs -v

# ---------------------------------------------------------------
# Step 5: Print manual steps for updating Proxmox storage
# ---------------------------------------------------------------
echo ""
echo "[5/5] Manual steps required — UPDATE STORAGE.CFG"
echo "========================================================"
echo ""
echo "⚠️  NFS is now exported from ${DR_NODE_NAME} (${DR_NODE_IP})."
echo "   But Proxmox storage.cfg still points to ${SHARED_NODE_IP}."
echo ""
echo "   From ANY cluster node, update each storage:"
echo ""

for ds in ${DR_DATASETS}; do
    STORAGE_ID=""
    # Map dataset name to storage ID
    case "${ds}" in
        vms)        STORAGE_ID="shared-vms" ;;
        kubernetes) STORAGE_ID="shared-k8s" ;;
        gitlab)     STORAGE_ID="shared-gitlab" ;;
        registry)   STORAGE_ID="shared-registry" ;;
        backups)    STORAGE_ID="shared-backups" ;;
    esac
    if [ -n "${STORAGE_ID}" ]; then
        echo "   pvesh set /storage/${STORAGE_ID} --server ${DR_NODE_IP}"
    fi
done

echo ""
echo "   Or use the Proxmox GUI: Datacenter → Storage → select storage → Edit → server IP"
echo ""
echo "=== T-17: Failover procedure initiated ==="
echo ""
echo "✅ DR datasets promoted to read-write"
echo "✅ NFS exported from ${DR_NODE_NAME} (${DR_NODE_IP})"
echo "⚠️  PENDING: Update Proxmox storage.cfg (manual step above)"
echo ""
echo "📋 After resolving the outage, run failback-to-desa03.sh"
echo "   to restore NFS service to ${SHARED_NODE_NAME}."
echo ""
echo "⚠️  IMPORTANT: Disable DR replication timer while in failover:"
echo "   systemctl stop zfs-replicate-dr.timer"
