#!/bin/bash
# ================================================================
# 04-bonding.sh — Task 3.4: Configure LACP bonding (pve-desa04)
# ================================================================
# Configures bonding mode 802.3ad (LACP) on pve-desa04, aggregating
# eno1-4 into bond0, then using bond0 as the bridge port for vmbr0.
#
# Topology: eno1 + eno2 + eno3 + eno4 ──LACP──→ bond0 ──→ vmbr0 ──→ VMs
#
# PREREQUISITE: Switch ports for eno1-4 on pve-desa04 MUST be
# configured as LACP members in the same bond/LAG group.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

echo "=== Task 3.4: Configurar bonding LACP en pve-desa04 ==="
echo ""

NODE_IP="${NODES[$BOND_NODE_IDX]}"
NODE_NAME="${NODE_NAMES[$BOND_NODE_IDX]}"
BOND_IFACE="bond0"

echo "  Nodo objetivo: ${NODE_NAME} (${NODE_IP})"
echo "  Interfaz bond: ${BOND_IFACE}"
echo "  Slaves: ${BOND_SLAVES[*]}"
echo "  Modo: ${BOND_MODE}"
echo ""

# ---------------------------------------------------------------
# Step 1: Verify prerequisites
# ---------------------------------------------------------------
echo "[1/6] Verificando prerequisitos..."

# Check connectivity
if ! ssh ${SSH_OPTS} root@${NODE_IP} "hostname" &>/dev/null; then
    echo "❌ ${NODE_NAME} no responde"
    exit 1
fi
echo "[1/6] ✅ Conectividad con ${NODE_NAME}"

# Check that specified NICs exist
for slave in "${BOND_SLAVES[@]}"; do
    NIC_EXISTS=$(ssh ${SSH_OPTS} root@${NODE_IP} "ip link show ${slave} 2>/dev/null | grep -c 'state'" || echo 0)
    if [ "${NIC_EXISTS}" -gt 0 ]; then
        echo "[1/6] ✅ ${slave}: existe en ${NODE_NAME}"
    else
        echo "[1/6] ❌ ${slave}: NO encontrado en ${NODE_NAME}"
        exit 1
    fi
done

# Check bonding module is available
BONDING_AVAILABLE=$(ssh ${SSH_OPTS} root@${NODE_IP} "lsmod | grep -c bonding || modprobe bonding 2>/dev/null && echo OK || echo NO" 2>/dev/null || echo "NO")
if [ "${BONDING_AVAILABLE}" = "OK" ]; then
    echo "[1/6] ✅ Módulo bonding disponible"
else
    echo "[1/6] ❌ Módulo bonding no disponible — instale con: modprobe bonding"
    exit 1
fi

# Check VLAN 10 exists (from Task 3.1)
VLAN_EXISTS=$(ssh ${SSH_OPTS} root@${NODE_IP} "grep -c '^iface ${VLAN_INTERFACE}' /etc/network/interfaces 2>/dev/null || echo 0")
if [ "${VLAN_EXISTS}" -gt 0 ]; then
    echo "[1/6] ✅ ${VLAN_INTERFACE} configurado (de Task 3.1)"
else
    echo "[1/6] ⚠️  ${VLAN_INTERFACE} no encontrado — asegúrese de ejecutar 01-vlan.sh primero"
    echo "   Continuando... La VLAN se mantiene sobre vmbr0 después del bonding."
fi

# ---------------------------------------------------------------
# Step 2: Backup interfaces
# ---------------------------------------------------------------
echo ""
echo "[2/6] Respaldando /etc/network/interfaces..."

BACKUP_SUFFIX=".bonding.backup.$(date +%Y%m%d_%H%M%S)"
ssh ${SSH_OPTS} root@${NODE_IP} "cp /etc/network/interfaces /etc/network/interfaces${BACKUP_SUFFIX}"
echo "[2/6] ✅ Respaldo: interfaces${BACKUP_SUFFIX}"

# ---------------------------------------------------------------
# Step 3: Generate new interfaces config
# ---------------------------------------------------------------
echo ""
echo "[3/6] Generando nueva configuración de red..."

# Read current interfaces
CURRENT_INTERFACES=$(ssh ${SSH_OPTS} root@${NODE_IP} "cat /etc/network/interfaces")

# Build the new configuration preserving loopback and vmbr0.10 (VLAN)
# but replacing the vmbr0 bridge-ports from eno1 to bond0
# and adding the bond0 interface definition.

# Strategy: Build a complete replacement file
NEW_INTERFACES=$(cat << INTERFACES_EOF
# /etc/network/interfaces — generated by Task 3.4 (bonding LACP)
# Backup: interfaces${BACKUP_SUFFIX}

# loopback
auto lo
iface lo inet loopback

# Bond LACP — aggregate eno1-4
auto bond0
iface bond0 inet manual
    bond-slaves $(IFS=' '; echo "${BOND_SLAVES[*]}")
    bond-mode ${BOND_MODE}
    bond-miimon ${BOND_MIIMON}
    bond-lacp-rate ${BOND_LACP_RATE}
    bond-xmit-hash-policy ${BOND_XMIT_HASH}

# Management bridge over bond0
auto vmbr0
iface vmbr0 inet static
    address ${BOND_NODE_IP}
    gateway ${BOND_GATEWAY}
    bridge-ports bond0
    bridge-stp off
    bridge-fd 0

# VLAN 10 — Corosync heartbeat (link1)
auto ${VLAN_INTERFACE}
iface ${VLAN_INTERFACE} inet static
    address ${VLAN_IPS[$BOND_NODE_IDX]}
    vlan-raw-device vmbr0
INTERFACES_EOF
)

echo "${NEW_INTERFACES}" | ssh ${SSH_OPTS} root@${NODE_IP} "cat > /tmp/interfaces.new"

# Show diff
echo "[3/6] Diferencias con configuración actual:"
ssh ${SSH_OPTS} root@${NODE_IP} "diff /etc/network/interfaces /tmp/interfaces.new 2>/dev/null || true"

# ---------------------------------------------------------------
# Step 4: Apply the new configuration
# ---------------------------------------------------------------
echo ""
echo "[4/6] Aplicando nueva configuración..."

# Replace interfaces file
ssh ${SSH_OPTS} root@${NODE_IP} "cp /tmp/interfaces.new /etc/network/interfaces"
echo "[4/6] ✅ /etc/network/interfaces actualizado"

# Apply the bond interface without full network restart
# 1. Load bonding module with proper mode
echo "[4/6] Creando interfaz bond0..."
ssh ${SSH_OPTS} root@${NODE_IP} "modprobe bonding mode=${BOND_MODE} miimon=${BOND_MIIMON}" 2>/dev/null || true

# 2. Create bond0 if not exists
BOND_EXISTS=$(ssh ${SSH_OPTS} root@${NODE_IP} "ip link show bond0 2>/dev/null | grep -c 'state'" || echo 0)
if [ "${BOND_EXISTS}" -eq 0 ]; then
    ssh ${SSH_OPTS} root@${NODE_IP} "ip link add bond0 type bond mode ${BOND_MODE} miimon ${BOND_MIIMON} lacp_rate ${BOND_LACP_RATE} xmit_hash_policy ${BOND_XMIT_HASH}" 2>/dev/null || {
        echo "⚠️  No se pudo crear bond0 vía iproute2 — se aplicará al reiniciar"
    }
fi

# 3. Set the bonding sysfs params
echo "[4/6] Configurando parámetros bonding..."
ssh ${SSH_OPTS} root@${NODE_IP} bash -s -- "${BOND_MODE}" "${BOND_MIIMON}" "${BOND_LACP_RATE}" "${BOND_XMIT_HASH}" "${BOND_SLAVES[*]}" << 'REMOTE'
    set -euo pipefail
    BOND_MODE="$1"
    BOND_MIIMON="$2"
    BOND_LACP_RATE="$3"
    BOND_XMIT_HASH="$4"
    BOND_SLAVES_STR="$5"

    if [ -d /sys/class/net/bond0 ]; then
        # Set mode first (must be before enslaving)
        echo "${BOND_MODE}" > /sys/class/net/bond0/bonding/mode 2>/dev/null || true
        echo "${BOND_MIIMON}" > /sys/class/net/bond0/bonding/miimon 2>/dev/null || true
        echo "${BOND_LACP_RATE}" > /sys/class/net/bond0/bonding/lacp_rate 2>/dev/null || true
        echo "${BOND_XMIT_HASH}" > /sys/class/net/bond0/bonding/xmit_hash_policy 2>/dev/null || true

        # Enslave NICs
        for slave in ${BOND_SLAVES_STR}; do
            # Check if already enslaved
            if ! grep -q "${slave}" /sys/class/net/bond0/bonding/slaves 2>/dev/null; then
                ip link set "${slave}" down || true
                echo "+${slave}" > /sys/class/net/bond0/bonding/slaves 2>/dev/null || {
                    echo "⚠️  No se pudo esclavizar ${slave} (posiblemente ya en uso)"
                }
            else
                echo "  ${slave} ya está en bond0"
            fi
        done

        # Bring bond0 up
        ip link set bond0 up
        echo "✅ bond0 configurado con slaves: $(cat /sys/class/net/bond0/bonding/slaves 2>/dev/null)"
    else
        echo "⚠️  bond0 no existe en sysfs — se configurará en el próximo reinicio"
    fi
REMOTE

# 4. Bridge vmbr0 to use bond0
# This requires replacing the bridge port — we may need to restart networking
# or do it more surgically.
echo "[4/6] Actualizando puente vmbr0 para usar bond0..."
# Check if vmbr0 exists
VMBR_EXISTS=$(ssh ${SSH_OPTS} root@${NODE_IP} "ip link show vmbr0 2>/dev/null | grep -c 'state'" || echo 0)
if [ "${VMBR_EXISTS}" -gt 0 ]; then
    # Remove current ports from bridge
    CURRENT_PORTS=$(ssh ${SSH_OPTS} root@${NODE_IP} "bridge link show vmbr0 2>/dev/null | awk '{print \$2}' | tr -d ':'" || echo "")
    for port in ${CURRENT_PORTS}; do
        ssh ${SSH_OPTS} root@${NODE_IP} "ip link set ${port} nomaster 2>/dev/null" || true
    done

    # Add bond0 as bridge port
    ssh ${SSH_OPTS} root@${NODE_IP} "ip link set bond0 master vmbr0 2>/dev/null" || {
        echo "⚠️  No se pudo agregar bond0 a vmbr0 en caliente"
        echo "   Esto es normal si el bridge ya está en uso — se completa en el próximo reinicio"
    }
    echo "[4/6] ✅ bond0 agregado como puerto de vmbr0"
else
    echo "[4/6] ⚠️  vmbr0 no existe — se creará al reiniciar la red"
fi

# ---------------------------------------------------------------
# Step 5: Test connectivity
# ---------------------------------------------------------------
echo ""
echo "[5/6] Verificando conectividad después del bonding..."

# Give the link time to establish LACP negotiation
echo "  Esperando negociación LACP (15s)..."
sleep 15

# Check bond status
BOND_STATUS=$(ssh ${SSH_OPTS} root@${NODE_IP} "cat /proc/net/bonding/bond0 2>/dev/null" || echo "NOT_FOUND")
if [ "${BOND_STATUS}" != "NOT_FOUND" ]; then
    echo "--- Bonding status on ${NODE_NAME} ---"
    echo "${BOND_STATUS}" | head -30 | sed 's/^/  /'
    echo ""

    # Count active slaves
    ACTIVE_SLAVES=$(echo "${BOND_STATUS}" | grep -c "MII Status: up" 2>/dev/null || echo 0)
    echo "[5/6] Slaves activos: ${ACTIVE_SLAVES}"
    if [ "${ACTIVE_SLAVES}" -ge 2 ]; then
        echo "[5/6] ✅ ${ACTIVE_SLAVES}/${#BOND_SLAVES[@]} slaves UP (LACP negociado)"
    else
        echo "[5/6] ⚠️  Solo ${ACTIVE_SLAVES}/${#BOND_SLAVES[@]} slaves UP"
        echo "   Verifique configuración de LACP en el switch"
    fi
else
    echo "[5/6] ⚠️  bond0 no operativo — verificar después del reinicio"
fi

# Test basic connectivity
echo ""
echo "[5/6] Probando conectividad de red..."
PING_OK=$(ssh ${SSH_OPTS} root@${NODE_IP} "ping -c 2 -W 2 192.168.1.1 2>/dev/null | grep -c '1 received\|2 received'" || echo 0)
if [ "${PING_OK}" -gt 0 ]; then
    echo "[5/6] ✅ Gateway accesible desde ${NODE_NAME}"
else
    echo "[5/6] ⚠️  Gateway no responde — la red puede estar caída en el bridge"
    echo "   Si la conectividad se pierde, el nodo recuperará la config previa al reiniciar"
    echo "   Backup disponible: interfaces${BACKUP_SUFFIX}"
    echo "   Para revertir: cp /etc/network/interfaces${BACKUP_SUFFIX} /etc/network/interfaces"
fi

# ---------------------------------------------------------------
# Step 6: Summary
# ---------------------------------------------------------------
echo ""
echo "[6/6] Resumen de configuración de bonding..."

echo "  Nodo: ${NODE_NAME}"
echo "  Bond: bond0 (${BOND_MODE})"
echo "  Slaves: ${BOND_SLAVES[*]}"
echo "  Bridge: vmbr0 → bond0"
echo "  VLAN 10: ${VLAN_INTERFACE}"
echo "  Backup: interfaces${BACKUP_SUFFIX}"

echo ""
echo "=== Task 3.4 completada ==="
echo ""
echo "⚠️  IMPORTANTE:"
echo "  1. Verifique que el switch tenga los puertos eno1-4 de ${NODE_NAME}"
echo "     configurados como miembros LACP del mismo LAG."
echo "  2. Si la conectividad se pierde, el cambio es PERSISTENTE en"
echo "     /etc/network/interfaces. Para revertir:"
echo "     cp /etc/network/interfaces${BACKUP_SUFFIX} /etc/network/interfaces"
echo "     reboot (o ifreload -a desde consola local)"
